### ISSUE TITLE
Blind singing without warning

### ISSUE THREAD

**Issue by n8mgr** [SiaFoundation/app-sia-x#8]
The application allows a user to sign a hash without custom configuration. Blind signing breaks the device threat model for many reasons explained [here](https://developers.ledger.com/docs/device-app/architecture/cryptography/general-concepts#avoid-blindly-signing-data).  
If blind singing is needed, a [special flow](https://developers.ledger.com/docs/device-app/deliver/deliverables/ui-flow-video#blind-signing) must be implemented that disables blind signing by default and refuses the associated commands. If the user really knows what he is doing he can then enable blind singing in the application parameters at his own risks.

**Recommendation:** This feature is not used by the SIA wallet (https://github.com/siacentral/ledgerjs-sia/blob/main/src/sia.ts). So if it's ever needed it can be removed from the code base. If it's still needed, the blind signing [requirements](https://developers.ledger.com/docs/device-app/develop/requirements/security#blind-signing) must be implemented to guarantee security by default.

**Comment by lukechampine** [comment]
Good call -- this was originally implemented because the normal signing flow only supports "simple" transactions (SC/SF inputs and outputs, with a miner fee), making it impossible to use a Ledger to sign e.g. a file contract or a Foundation subsidy address update. But those cases can be handled without introducing a fully-general signing flow (which is indeed much too easy for an attacker to take advantage of).
